/**
 * Site-wide content. Source: https://sumicitsolutions.com/ (fetched 2026-09-30).
 * Anything not found on the live site is marked with a `TODO:` value.
 */

export interface NavLink {
  label: string
  /** Canonical URL. Internal routes point at pages that will exist in later phases. */
  href: string
  /** Home page section this link represents. While the home page is the only page, links with a
   *  sectionId resolve to `#<sectionId>` (see `navHref` in lib/nav.ts) and drive the active state. */
  sectionId?: string
  external?: boolean
  children?: readonly NavLink[]
}

export interface SocialLink {
  platform: 'facebook' | 'x' | 'instagram' | 'linkedin' | 'youtube' | 'whatsapp'
  label: string
  href: string
}

export interface Product {
  name: string
  /** Category as labelled on the live site's "Sumic Ecosystem 2026" graphic. */
  category: string
  href: string
}

export interface SiteContent {
  name: string
  shortName: string
  tagline: string
  since: string
  description: string
  url: string
  /** One-line company description. */
  summary: string
  /** Sumic Group vision line. */
  vision: string
  logo: {
    /** Navy/green logo for light backgrounds. */
    src: string
    /** White/green logo for dark backgrounds. */
    inverseSrc: string
    width: number
    height: number
    alt: string
  }
  cta: NavLink
  contact: {
    address: string
    mapUrl: string
    email: string
    phone: { display: string; href: string }
    hours: string
  }
  nav: readonly NavLink[]
  footer: {
    quickLinks: readonly NavLink[]
    policies: readonly NavLink[]
    copyright: (year: number) => string
  }
  products: readonly Product[]
  social: readonly SocialLink[]
}

export const site: SiteContent = {
  name: 'Sumic IT Solutions Ltd',
  shortName: 'Sumic IT Solutions',
  tagline: 'Engineering the Future of Digital Solutions',
  since: 'Since 2019',
  description:
    'We are digital transformation solutions providers on the African Continent established in 2019. Developers of Sumic Online a robust e-commerce Platform.',
  url: 'https://sumicitsolutions.com',
  summary:
    'Sumic IT Solutions Ltd is a technology and digital transformation company building scalable software products, AI-powered platforms and enterprise solutions.',
  // Quote under the "Sumic Group" heading near the bottom of the live home page (confirmed by
  // Sumic; not present in the server HTML fetched 2026-09-30, likely rendered client-side).
  vision: 'A Self Sufficient Africa where everyone has an opportunity to thrive.',
  // Logos were pulled from the live site; replace with brand-kit originals when available.
  // The inverse version was generated by recolouring the navy strokes to white.
  logo: {
    src: '/brand/sumic-logo-320w.webp',
    inverseSrc: '/brand/sumic-logo-inverse-320w.webp',
    width: 320,
    height: 222,
    alt: 'Sumic IT Solutions',
  },
  // Live site's hero button ("Talk to us" -> /contact).
  cta: { label: 'Talk to us', href: '/contact', sectionId: 'cta' },
  contact: {
    address: 'New Port Bell Road, P.O.BOX 172928, Kampala GPO',
    mapUrl: 'https://goo.gl/maps/fvbsxE6NsJfnmGfz8',
    email: 'info@sumicitsolutions.com',
    phone: { display: '+256 200 930 793', href: 'tel:+256200930793' },
    hours: 'TODO: business hours not listed on the live site',
  },
  nav: [
    { label: 'Home', href: '/', sectionId: 'hero' },
    {
      label: 'Who We Are',
      href: '/about',
      sectionId: 'about',
      children: [
        { label: 'Governance', href: '/team' },
        { label: 'Sumic Meaning', href: '/sumic-meaning' },
        {
          label: 'Sumic Brand Kit',
          href: 'https://drive.google.com/drive/folders/1FOC2S_tCI3QX9mhSe5Uu4f8sSVdGu3ku?usp=sharing',
          external: true,
        },
        {
          label: 'Company Profile',
          href: 'https://sumicitsolutions.com/wp-content/uploads/2026/09/Sumic-IT-Solutions-Ltd-Company-Profile-2026-Vol-8.pdf',
          external: true,
        },
        { label: 'Meet The Founder', href: '/cirus-sumika' },
      ],
    },
    { label: 'What We Do', href: '/services', sectionId: 'services' },
    {
      label: 'Checklist Forms',
      href: '#',
      children: [
        {
          label: 'Website Checklist Form',
          href: 'https://forms.gle/tKaBT39AWJqJDHb98',
          external: true,
        },
        {
          label: 'Mobile App Checklist Form',
          href: 'https://forms.gle/bmbxCA1CLruqx9fG6',
          external: true,
        },
      ],
    },
    { label: 'Partnerships', href: '/sumic-partnerships' },
    { label: 'Careers', href: '/careers' },
  ],
  footer: {
    quickLinks: [
      { label: 'Home', href: '/' },
      { label: 'About Us', href: '/about' },
      { label: 'Contact Us', href: '/contact' },
      { label: 'Governance', href: '/team' },
      {
        label: 'Sumic Brand Kit',
        href: 'https://drive.google.com/drive/folders/1FOC2S_tCI3QX9mhSe5Uu4f8sSVdGu3ku?usp=sharing',
        external: true,
      },
      {
        label: 'WhatsApp Channel',
        href: 'https://whatsapp.com/channel/0029VaDI5bIA2pL2j9LsPh2U',
        external: true,
      },
    ],
    policies: [
      { label: 'Privacy Policy', href: '/privacy-policy' },
      { label: 'Cookies Policy', href: '/cookies-policy' },
      { label: 'Terms of Use Policy', href: '/terms-of-use' },
    ],
    copyright: (year) => `Copyright © ${year} Sumic IT Solutions Ltd. All Rights Reserved`,
  },
  products: [
    { name: 'Talent Kasi', category: 'HRTech & AI', href: 'https://talentkasi.com/' },
    { name: 'Sumic Online', category: 'e-Commerce', href: 'https://sumiconline.com/' },
    { name: 'SUMICode AI', category: 'EduTech & AI', href: 'https://sumicodeai.com/' },
    { name: 'Sumic International Academy', category: 'EduTech', href: 'https://sumicacademy.com/' },
    { name: 'EventsTrack', category: 'EventsTech', href: 'https://eventstrack.com/' },
    { name: 'Worket Jua Kali', category: 'Labour Tech', href: 'https://worketconnect.com/' },
  ],
  social: [
    {
      platform: 'facebook',
      label: 'Facebook',
      href: 'https://www.facebook.com/sumic.itsolutions/',
    },
    { platform: 'x', label: 'X (Twitter)', href: 'https://x.com/SumicUg' },
    {
      platform: 'instagram',
      label: 'Instagram',
      href: 'https://www.instagram.com/sumicitsolutions',
    },
    {
      platform: 'linkedin',
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/company/sumic-it-solutions/',
    },
    { platform: 'youtube', label: 'YouTube', href: 'https://www.youtube.com/@sumicitsolutions' },
    {
      platform: 'whatsapp',
      label: 'WhatsApp Channel',
      href: 'https://whatsapp.com/channel/0029VaDI5bIA2pL2j9LsPh2U',
    },
  ],
}
